# Generated by Django 4.2.30 on 2026-04-24 17:27

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_catalogo', models.CharField(max_length=150)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catálogo',
                'verbose_name_plural': 'Catálogos',
                'db_table': 'catalogos',
                'ordering': ['nombre_catalogo'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'permisos',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=150)),
                ('descripcion_producto', models.TextField(blank=True, null=True)),
                ('foto', models.CharField(blank=True, max_length=500, null=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('NO_DISPONIBLE', 'No Disponible')], default='DISPONIBLE', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('catalogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='AppMoa.catalogo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='AppMoa.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit_proveedor', models.BigIntegerField(unique=True)),
                ('nombre_proveedor', models.CharField(max_length=150)),
                ('telefono_proveedor', models.BigIntegerField()),
                ('correo_proveedor', models.EmailField(max_length=150)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
                'ordering': ['nombre_proveedor'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=150, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['nombre_rol'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_usuario', models.CharField(max_length=150)),
                ('apellidos_usuario', models.CharField(blank=True, max_length=150, null=True)),
                ('correo_usuario', models.EmailField(max_length=150, unique=True)),
                ('numero_documento', models.CharField(blank=True, max_length=150, null=True)),
                ('tipo_documento', models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('PA', 'Pasaporte'), ('NIT', 'NIT')], max_length=150, null=True)),
                ('contrasena', models.CharField(max_length=150)),
                ('estado_usuario', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=150)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='AppMoa.rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('descuento_fidelidad', models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('monto_iva', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('monto_final', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ventas', to='AppMoa.usuario')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='VariacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(max_length=5)),
                ('color', models.CharField(max_length=150)),
                ('sku_unico', models.CharField(max_length=150, unique=True)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('precio_base', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('iva_porcentaje', models.FloatField(default=19.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('stock_actual', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_minimo', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variaciones', to='AppMoa.producto')),
            ],
            options={
                'verbose_name': 'Variación de Producto',
                'verbose_name_plural': 'Variaciones de Producto',
                'db_table': 'variacion_producto',
                'ordering': ['producto', 'talla', 'color'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='productos', to='AppMoa.proveedor'),
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento_envio', models.CharField(max_length=150)),
                ('ciudad_envio', models.CharField(max_length=150)),
                ('barrio_envio', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion_envio', models.CharField(max_length=150)),
                ('tipo_vivienda', models.CharField(choices=[('CASA', 'Casa'), ('APARTAMENTO', 'Apartamento'), ('OFICINA', 'Oficina'), ('LOCAL', 'Local Comercial'), ('OTRO', 'Otro')], default='CASA', max_length=150)),
                ('especificaciones_llegada', models.TextField(blank=True, max_length=200, null=True)),
                ('telefono_llegada', models.CharField(max_length=200)),
                ('empresa_transportadora', models.CharField(blank=True, max_length=150, null=True)),
                ('numero_guia', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('estado_envio', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CAMINO', 'En Camino'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado'), ('DEVUELTO', 'Devuelto')], default='PENDIENTE', max_length=150)),
                ('fecha_envio', models.DateTimeField()),
                ('fecha_estipulada_llegada', models.DateField()),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='envios', to='AppMoa.usuario')),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='envio', to='AppMoa.venta')),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
                'db_table': 'envios',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField()),
                ('total_entrada', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='entradas', to='AppMoa.proveedor')),
            ],
            options={
                'verbose_name': 'Entrada de Inventario',
                'verbose_name_plural': 'Entradas de Inventario',
                'db_table': 'entradas',
                'ordering': ['-fecha_entrada'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('variacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='detalles_venta', to='AppMoa.variacionproducto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='AppMoa.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
                'db_table': 'detalle_venta',
            },
        ),
        migrations.CreateModel(
            name='DetalleEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidades', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_comprado', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='AppMoa.entrada')),
                ('variacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='detalles_entrada', to='AppMoa.variacionproducto')),
            ],
            options={
                'verbose_name': 'Detalle de Entrada',
                'verbose_name_plural': 'Detalles de Entrada',
                'db_table': 'detalle_entrada',
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol_permisos', to='AppMoa.permiso')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol_permisos', to='AppMoa.rol')),
            ],
            options={
                'verbose_name': 'Rol-Permiso',
                'verbose_name_plural': 'Roles-Permisos',
                'db_table': 'rol_permisos',
                'unique_together': {('rol', 'permiso')},
            },
        ),
    ]
