# Generated by Django 4.2.30 on 2026-04-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMoa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='descripcion_catalogo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
