# Generated by Django 5.2.7 on 2026-05-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMoa', '0002_catalogo_descripcion_catalogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='permisos',
            field=models.ManyToManyField(related_name='roles', through='AppMoa.RolPermiso', to='AppMoa.permiso'),
        ),
    ]
