# Generated by Django 5.2.7 on 2026-05-26 15:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMoa', '0003_rol_permisos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_reset', to='AppMoa.usuario')),
            ],
            options={
                'db_table': 'tokens_reset',
            },
        ),
    ]
