# Generated by Django 5.2.7 on 2026-06-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppMoa", "0004_tokenreset"),
    ]

    operations = [
        migrations.AddField(
            model_name="rol",
            name="confirmado",
            field=models.BooleanField(default=False),
        ),
    ]
