# Generated by Django 5.2.7 on 2026-06-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppMoa", "0005_rol_confirmado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rol",
            name="confirmado",
        ),
        migrations.AddField(
            model_name="venta",
            name="confirmado",
            field=models.BooleanField(default=False),
        ),
    ]
