# Generated by Django 5.2.7 on 2026-06-17 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppMoa", "0006_remove_rol_confirmado_venta_confirmado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venta",
            name="confirmado",
        ),
    ]
