# Generated by Django 5.2.7 on 2026-06-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppMoa", "0007_remove_venta_confirmado"),
    ]

    operations = [
        migrations.AddField(
            model_name="envio",
            name="confirmado_llegada",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="envio",
            name="fecha_confirmacion_llegada",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
